version: "2"
services:
  app:
    image: nasajon/ionic
    restart: always
    command: ionic serve -b
    depends_on:
      - install
    ports:
      - 8100:8100
      - 35729:35729
      - 53703:53703
    volumes:
      - ./:/ionic
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTP_PROXY
  install:
    image: nasajon/ionic
    command: yarn install
    volumes:
      - ./:/ionic
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTP_PROXY
  # jsonserver:
  #   image: vimagick/json-server
  #   restart: always
  #   command: -w db.json
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./db.json:/app/db.json
  # build:
  #   image: nasajon/ionic:android-sdk-ubuntu
  #   restart: always
  #   volumes:
  #     - ./:/build
  #   environment:
  #     - HTTP_PROXY=$HTTP_PROXY
  #     - HTTPS_PROXY=$HTTP_PROXY
